version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-intl
    versions:
    - 5.10.6
    - 5.12.5
    - 5.13.0
    - 5.13.1
    - 5.13.2
    - 5.13.3
    - 5.13.4
    - 5.13.5
    - 5.14.0
    - 5.15.3
    - 5.15.5
    - 5.15.7
    - 5.15.8
    - 5.16.0
    - 5.17.0
    - 5.17.1
  - dependency-name: meteor-node-stubs
    versions:
    - 1.0.1
    - 1.0.2
  - dependency-name: react-router-bootstrap
    versions:
    - 0.24.1
  - dependency-name: react-cookie
    versions:
    - 2.2.0
  - dependency-name: bcrypt
    versions:
    - 5.0.0
  - dependency-name: escape-string-regexp
    versions:
    - 4.0.0
